

// Generated on 03/23/2022 09:52:00
using System;
using System.Collections.Generic;

namespace AmaknaProxy.API.Protocol.Enums
{
    public enum GuildRightsEnum
    {
        RIGHT_MANAGE_RANKS_AND_RIGHTS = 1,
        RIGHT_MANAGE_CHEST_RIGHTS = 2,
        RIGHT_MANAGE_SELF_XP_CONTRIBUTION = 3,
        RIGHT_MANAGE_ALL_XP_CONTRIBUTION = 4,
        RIGHT_MANAGE_RECRUITMENT = 5,
        RIGHT_MANAGE_APPLY_AND_INVITATION = 6,
        RIGHT_UPDATE_MOTD = 7,
        RIGHT_OPEN_GUILD_CHEST = 8,
        RIGHT_MANAGE_BOOSTS = 9,
        RIGHT_USE_PADDOCKS = 10,
        RIGHT_SET_ALLIANCE_PRISM = 11,
        RIGHT_KICK_MEMBER = 13,
        RIGHT_MANAGE_MEMBERS_NOTE = 14,
        RIGHT_UPDATE_BULLETIN = 15,
        RIGHT_DEFENSE_PRIORITY = 16,
        RIGHT_HIRE_TAX_COLLECTOR = 17,
        RIGHT_COLLECT_TAX_COLLECTOR = 18,
        RIGHT_COLLECT_OWN_TAX_COLLECTOR = 19,
        RIGHT_MANAGE_PADDOCKS = 20,
        RIGHT_MANAGE_OTHER_MOUNTS = 21,
        RIGHT_TALK_IN_ALLIANCE_CHANNEL = 22,
        RIGHT_TAKE_FROM_GUILD_CHEST = 23,
        RIGHT_DROP_ON_GUILD_CHEST = 24,
        RIGHT_SHOW_TRANSACTION_PLAYER = 25,
        RIGHT_ASSIGN_RANKS = 26,
        RIGHT_BUY_FARM = 27,
    }
}